services:
  postgres:
    image: postgres:latest
    # user: "1000:1000"  # Match your host user and group
    environment:
      POSTGRES_USER: musebot_admin
      POSTGRES_PASSWORD: musebot_2024
      POSTGRES_DB: musebot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
    #  - "5173:5432"  # Bind PostgreSQL's internal 5432 port to host port 5173
    restart: always

  fastapi:
    user: "1000:1000"  # Match your host user and group
    build:
      context: ./app
      dockerfile: Dockerfile.fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://musebot_admin:musebot_2024@postgres/musebot_db
    depends_on:
      - postgres
      # - rasa
    volumes:
      - ./app:/app  # Mount local FastAPI project directory
    restart: always

  rasa:
    user: "1000:1000"  # Match your host user and group
    build:
      context: ./rasa
      dockerfile: Dockerfile.rasa
    ports:
      - "5005:5005"
    # command: 
    volumes:
      - ./rasa:/app  # Mount local Rasa project directory
    depends_on:
      - rasa_sdk
    restart: always

  rasa_sdk:
    user: "1000:1000"  # Match your host user and group
    build:
      context: ./rasa
      dockerfile: Dockerfile.rasa_sdk
    ports:
      - "5055:5055"
    volumes:
      - ./rasa/actions:/app/actions
      - ./rasa/endpoints.yml:/app/endpoints.yml
    restart: always

volumes:
  postgres_data:
