# Base image for Rasa SDK
FROM rasa/rasa-sdk:latest

# Set work directory
WORKDIR /app

# Copy action server files
COPY . /app

# Install additional Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose action server port
EXPOSE 5055

ENTRYPOINT ["/bin/sh", "-c"]
# Command to run Rasa SDK action server
CMD ["rasa-sdk", "run", "--port", "5055"]
