# Use the official Rasa image
FROM rasa/rasa:latest

# Temporarily switch to root to add group and user
USER root

# Create the group and user
RUN groupadd -g 1000 musebot_group && \
    useradd -u 1000 -g musebot_group -m musebot_user

# Set the working directory
WORKDIR /app



# Install additional Rasa dependencies if needed
# Uncomment if you have additional dependencies
# RUN pip install --no-cache-dir -r /app/requirements.txt

# Expose the necessary port
EXPOSE 5005

# Run Rasa server
CMD [ "run", "--enable-api", "--cors", "*" ,"--debug"]

# Run this command to train a new model
# CMD [ "train" ]

# Run this command to start the shell
# CMD [ "shell" ]

# Run this command to start the interactive training session
# CMD [ "interactive" ]